### ISSUE TITLE
Embedding the fonts as base64 encoded strings

### ISSUE THREAD

**Issue by hnrch02** [alfredxing/brick#10]
Have you considered embedding the fonts in the CSS file as base64 encoded strings? Until `HTTP/2.0` request are still pretty expensive.

**Comment by alfredxing** [comment]
Yes, I have. But: I'm using Fastly, a CDN, reverse proxy, and cache (it runs on Varnish).

Right now, by making separate requests for the fonts, they're able to cache the fonts on the network servers, to be available for any request.
By embedding the fonts as base64, it's a lot harder for the CDN to cache the response, since most people will be using a different set of fonts.

Consider two sites. The first site uses Open Sans Regular only, the second uses Open Sans Regular and Bold.
Their `link` tags would look like this:

``` html
<link rel="stylesheet" href="https://brick.a.ssl.fastly.net/Open+Sans:400">
```

``` html
<link rel="stylesheet" href="https://brick.a.ssl.fastly.net/Open+Sans:400,700">
```

By serving the fonts separately, visitors of both sites are able to retrieve the font from the closest server in the CDN network, whereas by embedding, it's a lot harder to generate a HIT, since visitors have to rely on that specific set of fonts being cached.

Embedding also greatly increases the space the cached requests takes up, and it also takes longer to generate the CSS.
